export const MechanicsList = [
  {
    id: 1,
    name: "Jack Thompson",
    specialization: "Engine Repair",
    experienceYears: 9,
    rating: 4.8,
    location: "Sydney, NSW",
  },
  {
    id: 2,
    name: "Liam Anderson",
    specialization: "Transmission Specialist",
    experienceYears: 11,
    rating: 4.9,
    location: "Melbourne, VIC",
  },
  {
    id: 3,
    name: "Ethan Williams",
    specialization: "Brake and Suspension",
    experienceYears: 7,
    rating: 4.6,
    location: "Brisbane, QLD",
  },
  {
    id: 4,
    name: "Noah Brown",
    specialization: "Electrical and Diagnostics",
    experienceYears: 10,
    rating: 4.9,
    location: "Perth, WA",
  },
  {
    id: 5,
    name: "Oliver Harris",
    specialization: "Air Conditioning and Cooling Systems",
    experienceYears: 6,
    rating: 4.5,
    location: "Adelaide, SA",
  },
  {
    id: 6,
    name: "Mason Clark",
    specialization: "Diesel Engine Specialist",
    experienceYears: 13,
    rating: 4.9,
    location: "Canberra, ACT",
  },
  {
    id: 7,
    name: "Harvey Lewis",
    specialization: "Body Work and Paint Restoration",
    experienceYears: 8,
    rating: 4.7,
    location: "Gold Coast, QLD",
  },
  {
    id: 8,
    name: "Lucas White",
    specialization: "Hybrid and EV Systems",
    experienceYears: 5,
    rating: 4.6,
    location: "Hobart, TAS",
  },
  {
    id: 9,
    name: "Henry Walker",
    specialization: "Wheel Alignment and Tyre Services",
    experienceYears: 7,
    rating: 4.5,
    location: "Darwin, NT",
  },
  {
    id: 10,
    name: "Charlie Martin",
    specialization: "General Service and Maintenance",
    experienceYears: 10,
    rating: 4.8,
    location: "Newcastle, NSW",
  },
  {
    id: 11,
    name: "James Foster",
    specialization: "Clutch and Gearbox Repairs",
    experienceYears: 9,
    rating: 4.7,
    location: "Geelong, VIC",
  },
  {
    id: 12,
    name: "Ryan Cooper",
    specialization: "Airbag and Safety Systems",
    experienceYears: 12,
    rating: 4.9,
    location: "Wollongong, NSW",
  },
  {
    id: 13,
    name: "Daniel Edwards",
    specialization: "Battery and Charging Systems",
    experienceYears: 6,
    rating: 4.6,
    location: "Toowoomba, QLD",
  },
  {
    id: 14,
    name: "Nathan Scott",
    specialization: "Diesel Engine Specialist",
    experienceYears: 14,
    rating: 4.9,
    location: "Ballarat, VIC",
  },
  {
    id: 15,
    name: "Benjamin Hughes",
    specialization: "Suspension and Steering",
    experienceYears: 8,
    rating: 4.7,
    location: "Townsville, QLD",
  },
  {
    id: 16,
    name: "Jacob Ward",
    specialization: "Air Conditioning Systems",
    experienceYears: 5,
    rating: 4.5,
    location: "Cairns, QLD",
  },
  {
    id: 17,
    name: "Logan Rogers",
    specialization: "Auto Electrical Systems",
    experienceYears: 10,
    rating: 4.8,
    location: "Sunshine Coast, QLD",
  },
  {
    id: 18,
    name: "Jackson Hill",
    specialization: "Hybrid and EV Systems",
    experienceYears: 7,
    rating: 4.6,
    location: "Darwin, NT",
  },
  {
    id: 19,
    name: "Elijah Phillips",
    specialization: "Body Work and Paint",
    experienceYears: 9,
    rating: 4.8,
    location: "Rockhampton, QLD",
  },
  {
    id: 20,
    name: "Sebastian Young",
    specialization: "Exhaust Systems",
    experienceYears: 11,
    rating: 4.7,
    location: "Mackay, QLD",
  },
  {
    id: 21,
    name: "Hunter Parker",
    specialization: "Diagnostics and Tuning",
    experienceYears: 10,
    rating: 4.9,
    location: "Bendigo, VIC",
  },
  {
    id: 22,
    name: "Samuel Baker",
    specialization: "Brake Systems",
    experienceYears: 6,
    rating: 4.5,
    location: "Launceston, TAS",
  },
  {
    id: 23,
    name: "Isaac Adams",
    specialization: "Engine Overhaul",
    experienceYears: 8,
    rating: 4.8,
    location: "Ballina, NSW",
  },
  {
    id: 24,
    name: "Owen Campbell",
    specialization: "Fuel Injection Systems",
    experienceYears: 7,
    rating: 4.6,
    location: "Albury, NSW",
  },
  {
    id: 25,
    name: "Matthew Stewart",
    specialization: "Air Conditioning and Cooling",
    experienceYears: 5,
    rating: 4.4,
    location: "Darwin, NT",
  },
  {
    id: 26,
    name: "Caleb Murphy",
    specialization: "Engine Diagnostics",
    experienceYears: 9,
    rating: 4.8,
    location: "Perth, WA",
  },
  {
    id: 27,
    name: "Luke Mitchell",
    specialization: "Diesel Engine Repair",
    experienceYears: 12,
    rating: 4.9,
    location: "Fremantle, WA",
  },
  {
    id: 28,
    name: "Aaron Cox",
    specialization: "Hybrid Systems",
    experienceYears: 6,
    rating: 4.6,
    location: "Canberra, ACT",
  },
  {
    id: 29,
    name: "Tyler Ward",
    specialization: "Wheel Alignment",
    experienceYears: 7,
    rating: 4.5,
    location: "Newcastle, NSW",
  },
  {
    id: 30,
    name: "Austin Morgan",
    specialization: "Transmission Repair",
    experienceYears: 9,
    rating: 4.8,
    location: "Sydney, NSW",
  },
  {
    id: 31,
    name: "Zachary James",
    specialization: "Brake Specialist",
    experienceYears: 10,
    rating: 4.8,
    location: "Melbourne, VIC",
  },
  {
    id: 32,
    name: "Connor Bell",
    specialization: "Exhaust Systems",
    experienceYears: 8,
    rating: 4.7,
    location: "Brisbane, QLD",
  },
  {
    id: 33,
    name: "Aiden Ross",
    specialization: "Electrical Systems",
    experienceYears: 5,
    rating: 4.5,
    location: "Adelaide, SA",
  },
  {
    id: 34,
    name: "Blake Wood",
    specialization: "Diagnostics",
    experienceYears: 9,
    rating: 4.9,
    location: "Perth, WA",
  },
  {
    id: 35,
    name: "Harrison Bennett",
    specialization: "Body Paint",
    experienceYears: 7,
    rating: 4.6,
    location: "Hobart, TAS",
  },
  {
    id: 36,
    name: "Levi Watson",
    specialization: "General Maintenance",
    experienceYears: 6,
    rating: 4.4,
    location: "Sydney, NSW",
  },
  {
    id: 37,
    name: "Jayden Brooks",
    specialization: "Clutch Repairs",
    experienceYears: 8,
    rating: 4.7,
    location: "Melbourne, VIC",
  },
  {
    id: 38,
    name: "Gabriel Kelly",
    specialization: "Transmission",
    experienceYears: 10,
    rating: 4.9,
    location: "Brisbane, QLD",
  },
  {
    id: 39,
    name: "Lincoln Reed",
    specialization: "Fuel Systems",
    experienceYears: 9,
    rating: 4.8,
    location: "Adelaide, SA",
  },
  {
    id: 40,
    name: "Eli Jenkins",
    specialization: "Air Conditioning",
    experienceYears: 5,
    rating: 4.5,
    location: "Canberra, ACT",
  },
  {
    id: 41,
    name: "Grayson Turner",
    specialization: "Diesel Engines",
    experienceYears: 12,
    rating: 4.9,
    location: "Perth, WA",
  },
  {
    id: 42,
    name: "Cooper Hayes",
    specialization: "Body Work",
    experienceYears: 6,
    rating: 4.5,
    location: "Gold Coast, QLD",
  },
  {
    id: 43,
    name: "Joshua Simmons",
    specialization: "Wheel Alignment",
    experienceYears: 7,
    rating: 4.6,
    location: "Cairns, QLD",
  },
  {
    id: 44,
    name: "Adam Russell",
    specialization: "Suspension",
    experienceYears: 8,
    rating: 4.7,
    location: "Newcastle, NSW",
  },
  {
    id: 45,
    name: "Charles Price",
    specialization: "Exhaust & Emissions",
    experienceYears: 10,
    rating: 4.9,
    location: "Sydney, NSW",
  },
  {
    id: 46,
    name: "Patrick Butler",
    specialization: "Diagnostics",
    experienceYears: 9,
    rating: 4.8,
    location: "Melbourne, VIC",
  },
  {
    id: 47,
    name: "Thomas Gray",
    specialization: "Electrical Systems",
    experienceYears: 11,
    rating: 4.9,
    location: "Brisbane, QLD",
  },
  {
    id: 48,
    name: "Joseph Ward",
    specialization: "Hybrid Systems",
    experienceYears: 7,
    rating: 4.6,
    location: "Canberra, ACT",
  },
  {
    id: 49,
    name: "Anthony Hughes",
    specialization: "Transmission",
    experienceYears: 12,
    rating: 4.9,
    location: "Adelaide, SA",
  },
  {
    id: 50,
    name: "Nicholas Cox",
    specialization: "General Service",
    experienceYears: 10,
    rating: 4.8,
    location: "Hobart, TAS",
  },
  {
    id: 51,
    name: "Elijah Cook",
    specialization: "Brake Systems",
    experienceYears: 9,
    rating: 4.8,
    location: "Sydney, NSW",
  },
  {
    id: 52,
    name: "Mason Foster",
    specialization: "Clutch Repair",
    experienceYears: 7,
    rating: 4.6,
    location: "Melbourne, VIC",
  },
  {
    id: 53,
    name: "Logan Perry",
    specialization: "Engine Diagnostics",
    experienceYears: 10,
    rating: 4.9,
    location: "Brisbane, QLD",
  },
  {
    id: 54,
    name: "Carter Bailey",
    specialization: "Body Work",
    experienceYears: 6,
    rating: 4.4,
    location: "Perth, WA",
  },
  {
    id: 55,
    name: "Jackson James",
    specialization: "Suspension",
    experienceYears: 8,
    rating: 4.7,
    location: "Adelaide, SA",
  },
  {
    id: 56,
    name: "Lucas Brown",
    specialization: "Diesel Engines",
    experienceYears: 9,
    rating: 4.8,
    location: "Canberra, ACT",
  },
  {
    id: 57,
    name: "Michael Adams",
    specialization: "Electrical Diagnostics",
    experienceYears: 13,
    rating: 5.0,
    location: "Darwin, NT",
  },
  {
    id: 58,
    name: "David Allen",
    specialization: "Air Conditioning",
    experienceYears: 6,
    rating: 4.5,
    location: "Gold Coast, QLD",
  },
  {
    id: 59,
    name: "Andrew Nelson",
    specialization: "Wheel Alignment",
    experienceYears: 8,
    rating: 4.6,
    location: "Melbourne, VIC",
  },
  {
    id: 60,
    name: "Joshua Rogers",
    specialization: "Body Paint",
    experienceYears: 10,
    rating: 4.8,
    location: "Sydney, NSW",
  },
  {
    id: 61,
    name: "Matthew Lee",
    specialization: "Engine Overhaul",
    experienceYears: 11,
    rating: 4.9,
    location: "Adelaide, SA",
  },
  {
    id: 62,
    name: "Joseph Scott",
    specialization: "Diagnostics",
    experienceYears: 7,
    rating: 4.6,
    location: "Perth, WA",
  },
  {
    id: 63,
    name: "Christopher White",
    specialization: "Brake Systems",
    experienceYears: 8,
    rating: 4.7,
    location: "Hobart, TAS",
  },
  {
    id: 64,
    name: "Alexander Green",
    specialization: "Transmission",
    experienceYears: 9,
    rating: 4.8,
    location: "Brisbane, QLD",
  },
  {
    id: 65,
    name: "Nathan Thompson",
    specialization: "Hybrid Systems",
    experienceYears: 10,
    rating: 4.9,
    location: "Canberra, ACT",
  },
  {
    id: 66,
    name: "Ryan Hill",
    specialization: "Diesel Engine Repair",
    experienceYears: 6,
    rating: 4.5,
    location: "Melbourne, VIC",
  },
  {
    id: 67,
    name: "Benjamin Carter",
    specialization: "Air Conditioning",
    experienceYears: 7,
    rating: 4.6,
    location: "Adelaide, SA",
  },
  {
    id: 68,
    name: "Jacob Wilson",
    specialization: "Body Work",
    experienceYears: 9,
    rating: 4.8,
    location: "Perth, WA",
  },
  {
    id: 69,
    name: "Thomas Mitchell",
    specialization: "General Maintenance",
    experienceYears: 10,
    rating: 4.8,
    location: "Sydney, NSW",
  },
  {
    id: 70,
    name: "Daniel Robinson",
    specialization: "Exhaust Systems",
    experienceYears: 8,
    rating: 4.7,
    location: "Melbourne, VIC",
  },
  {
    id: 71,
    name: "William Clark",
    specialization: "Wheel Alignment",
    experienceYears: 6,
    rating: 4.5,
    location: "Gold Coast, QLD",
  },
  {
    id: 72,
    name: "James Harris",
    specialization: "Engine Repair",
    experienceYears: 9,
    rating: 4.9,
    location: "Canberra, ACT",
  },
  {
    id: 73,
    name: "Michael Lewis",
    specialization: "Electrical Diagnostics",
    experienceYears: 12,
    rating: 4.9,
    location: "Adelaide, SA",
  },
  {
    id: 74,
    name: "David King",
    specialization: "Transmission",
    experienceYears: 10,
    rating: 4.8,
    location: "Sydney, NSW",
  },
  {
    id: 75,
    name: "Christopher Baker",
    specialization: "Fuel Systems",
    experienceYears: 11,
    rating: 4.9,
    location: "Melbourne, VIC",
  },
  {
    id: 76,
    name: "Matthew Allen",
    specialization: "Brake Repair",
    experienceYears: 8,
    rating: 4.7,
    location: "Brisbane, QLD",
  },
  {
    id: 77,
    name: "Andrew Wright",
    specialization: "Suspension",
    experienceYears: 6,
    rating: 4.5,
    location: "Adelaide, SA",
  },
  {
    id: 78,
    name: "Joshua Hall",
    specialization: "Diagnostics",
    experienceYears: 9,
    rating: 4.8,
    location: "Perth, WA",
  },
  {
    id: 79,
    name: "Joseph Young",
    specialization: "Hybrid Systems",
    experienceYears: 10,
    rating: 4.9,
    location: "Hobart, TAS",
  },
  {
    id: 80,
    name: "Ryan Thompson",
    specialization: "Air Conditioning",
    experienceYears: 7,
    rating: 4.6,
    location: "Canberra, ACT",
  },
  {
    id: 81,
    name: "Brandon Adams",
    specialization: "Diesel Engine Repair",
    experienceYears: 11,
    rating: 4.9,
    location: "Melbourne, VIC",
  },
  {
    id: 82,
    name: "Patrick Lee",
    specialization: "Electrical Systems",
    experienceYears: 8,
    rating: 4.7,
    location: "Sydney, NSW",
  },
  {
    id: 83,
    name: "Zachary Hall",
    specialization: "Wheel Alignment",
    experienceYears: 5,
    rating: 4.4,
    location: "Adelaide, SA",
  },
  {
    id: 84,
    name: "Aaron Scott",
    specialization: "General Service",
    experienceYears: 9,
    rating: 4.8,
    location: "Brisbane, QLD",
  },
  {
    id: 85,
    name: "Sean Walker",
    specialization: "Body Paint",
    experienceYears: 8,
    rating: 4.7,
    location: "Perth, WA",
  },
  {
    id: 86,
    name: "Tyler Phillips",
    specialization: "Transmission",
    experienceYears: 10,
    rating: 4.9,
    location: "Hobart, TAS",
  },
  {
    id: 87,
    name: "Ethan Robinson",
    specialization: "Suspension",
    experienceYears: 7,
    rating: 4.6,
    location: "Canberra, ACT",
  },
  {
    id: 88,
    name: "Austin Cooper",
    specialization: "Brake Systems",
    experienceYears: 6,
    rating: 4.5,
    location: "Melbourne, VIC",
  },
  {
    id: 89,
    name: "Cameron Mitchell",
    specialization: "Diagnostics",
    experienceYears: 9,
    rating: 4.8,
    location: "Sydney, NSW",
  },
  {
    id: 90,
    name: "Dylan Hughes",
    specialization: "Engine Repair",
    experienceYears: 11,
    rating: 4.9,
    location: "Brisbane, QLD",
  },
  {
    id: 91,
    name: "Eli Murphy",
    specialization: "Diesel Engines",
    experienceYears: 8,
    rating: 4.7,
    location: "Adelaide, SA",
  },
  {
    id: 92,
    name: "Nathan James",
    specialization: "Hybrid Systems",
    experienceYears: 9,
    rating: 4.8,
    location: "Canberra, ACT",
  },
  {
    id: 93,
    name: "Logan Kelly",
    specialization: "Electrical Systems",
    experienceYears: 10,
    rating: 4.9,
    location: "Melbourne, VIC",
  },
  {
    id: 94,
    name: "Jack Stewart",
    specialization: "Transmission",
    experienceYears: 6,
    rating: 4.5,
    location: "Sydney, NSW",
  },
  {
    id: 95,
    name: "Noah Edwards",
    specialization: "Suspension",
    experienceYears: 8,
    rating: 4.7,
    location: "Brisbane, QLD",
  },
  {
    id: 96,
    name: "Luke Campbell",
    specialization: "Air Conditioning",
    experienceYears: 7,
    rating: 4.6,
    location: "Adelaide, SA",
  },
  {
    id: 97,
    name: "Henry Gray",
    specialization: "Diagnostics",
    experienceYears: 9,
    rating: 4.8,
    location: "Perth, WA",
  },
  {
    id: 98,
    name: "Oliver Ross",
    specialization: "Brake Systems",
    experienceYears: 5,
    rating: 4.4,
    location: "Canberra, ACT",
  },
  {
    id: 99,
    name: "William Bennett",
    specialization: "Hybrid Systems",
    experienceYears: 10,
    rating: 4.9,
    location: "Sydney, NSW",
  },
  {
    id: 100,
    name: "Thomas Nelson",
    specialization: "General Maintenance",
    experienceYears: 12,
    rating: 4.9,
    location: "Melbourne, VIC",
  },
];
